"""Narrow contracts; production code contains no synthetic authentication."""
from contextlib import AbstractContextManager
from typing import Protocol
from radhouse.domain.access import Access, Binding, BotProfile
from radhouse.domain.releases import Publication, Review
from radhouse.domain.tasks import (AgentDispatch, Attempt, Delivery, EffectResult, Event,
    Operation, ProviderDescription, RuntimeCapabilities, RuntimeDispatch, RuntimeResult,
    SavedCommand, Task)


class UnitOfWork(Protocol):
    def access(self, principal_id: str) -> Access | None: ...
    def binding(self, channel: str, subject: str, conversation_id: str) -> Binding | None: ...
    def task(self, task_id: str) -> Task | None: ...
    def tasks(self) -> list[Task]: ...
    def bots(self, principal_id: str) -> list[BotProfile]: ...
    def insert_task(self, task: Task) -> None: ...
    def save_task(self, task: Task, expected_state_revision: int) -> None: ...
    def command(self, principal_id: str, command_key: str) -> SavedCommand | None: ...
    def save_command(self, command: SavedCommand) -> None: ...
    def delivery(self, channel: str, event_id: str) -> Delivery | None: ...
    def save_delivery(self, delivery: Delivery) -> None: ...
    def claim(self, task: Task, attempt: Attempt) -> bool: ...
    def attempt(self, attempt_id: str) -> Attempt | None: ...
    def finish_attempt(self, attempt_id: str) -> None: ...
    def operation(self, key: str) -> Operation | None: ...
    def save_operation(self, operation: Operation) -> None: ...
    def dispatch(self, key: str) -> AgentDispatch | None: ...
    def save_dispatch(self, dispatch: AgentDispatch) -> None: ...
    def add_event(self, event: Event) -> None: ...
    def events(self, task_id: str, after: int) -> list[Event]: ...
    def review(self, review_id: str) -> Review | None: ...
    def save_review(self, review: Review) -> None: ...
    def publication(self, task_id: str) -> Publication | None: ...
    def publish(self, publication: Publication) -> None: ...


class Store(Protocol):
    def transaction(self) -> AbstractContextManager[UnitOfWork]: ...


class AgentWorkPort(Protocol):
    def capabilities(self) -> RuntimeCapabilities: ...
    def start_or_attach(
        self, task: Task, attempt: Attempt, dispatch_key: str
    ) -> RuntimeDispatch: ...
    def result(self, dispatch: RuntimeDispatch) -> RuntimeResult: ...
    def stop(self, dispatch: RuntimeDispatch) -> bool: ...


class ProviderPort(Protocol):
    def describe(self, binding: str) -> ProviderDescription: ...


class OperationsPort(Protocol):
    def execute(self, task: Task, operation_key: str) -> EffectResult: ...
    def lookup(self, operation_key: str) -> EffectResult: ...
